### ISSUE TITLE
calculating pixels and percentages throws err

### ISSUE THREAD

**Issue by clp3777** [atomicpages/skeleton-sass#25]
[skeleton-sass/skeleton/themes/fresh/_skeleton.scss  - line 34](https://github.com/atomicpages/skeleton-sass/blob/master/skeleton/themes/fresh/_skeleton.scss#L34), 

$tablet-width returns a value in pixels while $base-width returns a percentage value... when compiled it throws CSS errors:

"Expecting RtPAREN" & "Unexpected token '99%'", plus 3 other "Unexpected token" errors.

When I manually change the outputted file to say ".99" the errors all clear.

BTW, I am a noob and trying to learn... thanks for the tutorials and such

**Comment by atomicpages** [comment]
@clp3777 I don't think this should matter when creating a media query? Are you using default values? If you're not can you provide some steps on how to reproduce the issue?

**Comment by clp3777** [comment]
I haven't made any changes to any of the installed files.  I have used the directory tree that you have assumed in the tuts... the only change I have made whilst following the tutorial is to the lines of code you use in _loader.scss which have a folder-name typo in them.  (You have "skeleton-sass" instead of skeleton-sass-official", as they are named in npm)...

I think that the issue may lie with Dreamweaver's linters.  I have noticed that many scripts written by accomplished coders throw errors.  For example, Dreamweaver is very strict with wanting defined vars, using proper {} with for loops, conditionals and while statements, and now it is giving me issues with the math results from the processed css files derived from the sass files you provided...

To recreate it I could possibly screenshot or capture a youtube vid if that would help you help me... like I said, I am new to a lot of this... I haven't created a website or coded in quite some time and a lot of what I learned I've forgotten.  I used to be proficient enough in php, as3 for flash, and CSS and basic HTML.  I'm more of a designer/artist than I am a developer, but, as they say, every designer should have basic developer skills... so I am eagerly trying to relearn.   I am trying to develop a responsive portfolio website... I have decided the skeleton framework is the most simple to implement for my purposes as I have used it before in a previous website... but everything in the old site breaks when I update jquery to latest version.

**Comment by atomicpages** [comment]
@clp3777 Skeleton Sass isn't causing any compile warnings/errors with libsass or sass 3.4.x (the official gem). This seems like an inspection error with DW. I'd recommend any of these free, cross-platform alternative text editors in lieu of DW:

* [Visual Studio Code](https://code.visualstudio.com/) (what Skeleton Sass is developed with)
* [Atom](https://atom.io/) (what Skeleton Sass used to be developed with)
* [Sublime Text 3](https://www.sublimetext.com/3) (what Skeleton Sass was originally developed with)

If you want a full-featured IDE then [Webstorm](https://www.jetbrains.com/webstorm/) is the way to go if you're willing to shell out the cash (if you have a student email address you can get this for free).

At the end of the day, as long as you're able to transcompile Sass into CSS, then you should be fine despite any text editors/IDEs bemoaning. Also, you might want to check out [jQuery Migration Tools](https://github.com/jquery/jquery-migrate) to help you out with that. Also, I'd recommend you to bookmark [caniuse.com](http://caniuse.com/) for searching browser compatibility with CSS stuff and JavaScript APIs alike. Lastly, another bookmark-worthy reference is [youmightnotneedjquery.com](http://youmightnotneedjquery.com/). If you look at the [`gh-pages`](https://github.com/atomicpages/skeleton-sass/tree/gh-pages) branch you'll see that I don't use jQuery since the site is simple (may not apply to your project).

As for those typos, feel free to contribute to the docs and fix any clerical errors I made!  👍  

At any rate, feel free to reach out to me at any time: atomicpages [at] gmail [dot] com

**Comment by clp3777** [comment]
Many thanks for the advice, I will look into these resources you suggested right now.  I'm not quite comfortable yet with using github and making contribs... I don't want to step on people's work and muck things up when I am unsure of my own skills... even for minor typos that may or may not be redirected url's that I wouldn't be able to know the difference :)

Again, thank you for your contributions and sharing with the community, your tutorials are helpful to me :)
